In [4]:
#creating frequency distribution of words using nltk
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
text="""Achievers are not afraid of Challenges, rather they relish them, thrive in them, use them. Challenges makes is stronger.
        Challenges makes us uncomfortable. If you get comfortable with uncomfort then you will grow. Challenge the challenge """

In [6]:
text

'Achievers are not afraid of Challenges, rather they relish them, thrive in them, use them. Challenges makes is stronger.\n        Challenges makes us uncomfortable. If you get comfortable with uncomfort then you will grow. Challenge the challenge '

In [7]:
#tokenize the sentences from the text corpus
tokenized_text = sent_tokenize(text)

In [8]:
tokenized_text

['Achievers are not afraid of Challenges, rather they relish them, thrive in them, use them.',
 'Challenges makes is stronger.',
 'Challenges makes us uncomfortable.',
 'If you get comfortable with uncomfort then you will grow.',
 'Challenge the challenge']

In [10]:
#tokenize the words from the sentences
tokenized_word = word_tokenize(text)

In [11]:
tokenized_word

['Achievers',
 'are',
 'not',
 'afraid',
 'of',
 'Challenges',
 ',',
 'rather',
 'they',
 'relish',
 'them',
 ',',
 'thrive',
 'in',
 'them',
 ',',
 'use',
 'them',
 '.',
 'Challenges',
 'makes',
 'is',
 'stronger',
 '.',
 'Challenges',
 'makes',
 'us',
 'uncomfortable',
 '.',
 'If',
 'you',
 'get',
 'comfortable',
 'with',
 'uncomfort',
 'then',
 'you',
 'will',
 'grow',
 '.',
 'Challenge',
 'the',
 'challenge']

In [13]:
#using count vectorizer and removing stopwords in english language
cv = CountVectorizer(lowercase=True, stop_words='english')

In [14]:
cv

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [16]:
#fitting the tokenized sentences to the countvectorizer
text_counts=cv.fit_transform(tokenized_text)

In [17]:
text_counts

<5x13 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [18]:
#printing the vocabulary and the frequency distribution pf vocabulary in tokenized sentences
print(cv.vocabulary_)
print(text_counts.toarray())

{'achievers': 0, 'afraid': 1, 'challenges': 3, 'relish': 7, 'thrive': 9, 'use': 12, 'makes': 6, 'stronger': 8, 'uncomfortable': 11, 'comfortable': 4, 'uncomfort': 10, 'grow': 5, 'challenge': 2}
[[1 1 0 1 0 0 0 1 0 1 0 0 1]
 [0 0 0 1 0 0 1 0 1 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 1 1 0 0 0 0 1 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 0 0]]
