In [1]:
#importing the libraries
import numpy as np
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding
from keras.layers import Dense
from keras.layers import Flatten

Using TensorFlow backend.


In [2]:
#define document
docs = ['Well done!',
        'Good work',
        'Great effort',
        'Nice job',
        'Excellent',
        'Weak',
        'Poor effort',
        'Not good',
        'Poor work',
        'Could have done better.']

In [3]:
#define the class labels
lables = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
#integer encode size vocabulary size
voc_size = 10000

# One Hot Representation

In [5]:
#word will getting the index from the dictionary
onehot_repr=[one_hot(words,voc_size)for words in docs]

In [6]:
onehot_repr

[[7816, 4894],
 [726, 7723],
 [4530, 6189],
 [2925, 6359],
 [9640],
 [9396],
 [4457, 6189],
 [5984, 726],
 [4457, 7723],
 [9684, 9424, 4894, 8356]]

In [7]:
#pad documents to a max length of words
max_length = 8
pad_docs = pad_sequences(onehot_repr, padding='pre',maxlen=max_length)

In [8]:
pad_docs

array([[   0,    0,    0,    0,    0,    0, 7816, 4894],
       [   0,    0,    0,    0,    0,    0,  726, 7723],
       [   0,    0,    0,    0,    0,    0, 4530, 6189],
       [   0,    0,    0,    0,    0,    0, 2925, 6359],
       [   0,    0,    0,    0,    0,    0,    0, 9640],
       [   0,    0,    0,    0,    0,    0,    0, 9396],
       [   0,    0,    0,    0,    0,    0, 4457, 6189],
       [   0,    0,    0,    0,    0,    0, 5984,  726],
       [   0,    0,    0,    0,    0,    0, 4457, 7723],
       [   0,    0,    0,    0, 9684, 9424, 4894, 8356]])

In [9]:
#define the model
model = Sequential()

In [10]:
#Adding the embedded layer and hidden layer and mension the dimensions
dim = 10
model.add(Embedding(voc_size, 10, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [11]:
model

In [19]:
#remove the warnings
import warnings
warnings.filterwarnings('ignore')
#compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [20]:
#to see the structure of model
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
_________________________________________________________________
flatten_1 (Flatten)          (None, 80)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 81        
Total params: 100,081
Trainable params: 100,081
Non-trainable params: 0
_________________________________________________________________


In [21]:
#fit the model
model.fit(pad_docs, lables, epochs=50, verbose=0)
#evaluate the model
loss, accuracy = model.evaluate(pad_docs, lables, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000


In [15]:
print(model.predict(pad_docs))

[[0.55655354]
 [0.5209984 ]
 [0.52385813]
 [0.5596578 ]
 [0.5257998 ]
 [0.48427138]
 [0.48662147]
 [0.4737434 ]
 [0.4886681 ]
 [0.41020393]]


In [16]:
pad_docs[0]

array([   0,    0,    0,    0,    0,    0, 7816, 4894])

In [17]:
pad_docs[2]

array([   0,    0,    0,    0,    0,    0, 4530, 6189])

In [18]:
print(model.predict(pad_docs)[2])

[0.52385813]
